version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mini-trello-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mini_trello
      MYSQL_USER: trello_user
      MYSQL_PASSWORD: trello_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mini-trello-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  mini-trello-network:
    driver: bridge
